// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.5.5.5.5.5.55.5.5.5.5.5.
5.......................
........................
5.......................
........................
5.......................
........................
5.......................
........................
5.......................
........................
5..........33...........
5..........33...........
........................
5.......................
........................
5.......................
........................
5.......................
........................
5.......................
........................
5.......................
........................
`;
            case "image2":
            case "myImage0":return img`
........................
........................
........................
...fff....cccc....fff...
...fddccccddddccccddf...
...fddddddddddddddddf...
....cddddddddddddddc....
....cdddbbbbbbbbdddc....
....cddbddddddddbddc....
....cddbddddddddbddc....
...cdddbd33dd33dbdddc...
...cdddbd333333dbdddc...
...cdddbd333333dbdddc...
...cdddbdd3333ddbdddc...
....cddbddd33dddbddc....
....cddbddddddddbddc....
....cdddbbbbbbbbdddc....
....cddddddddddddddc....
...fddddddddddddddddf...
...fddccccddddccccddf...
...fff....cccc....fff...
........................
........................
........................
`;
            case "image3":
            case "myImage1":return img`
........................
........................
........................
...fff....cccc....fff...
...f11cccc1111ccccddf...
...f1111111111ddddddf...
....c1111111dddddddc....
....c111dddbbbbbdddc....
....c11d111dddddbddc....
....c11d11ddddddbddc....
...c111d133dd33dbdddc...
...c111bd333333dbdddc...
...c111bd333333dbdddc...
...cdddbdd3333ddbdddc...
....cddbddd33dddbddc....
....cddbddddddddbddc....
....cdddbbbbbbbbdddc....
....cddddddddddddddc....
...fddddddddddddddddf...
...fddccccddddccccddf...
...fff....cccc....fff...
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
